name: Manual CI (Linux)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install sshpass
        continue-on-error: true
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Change root password
        continue-on-error: true
        run: echo 'root:admin' | sudo chpasswd

      - name: Enable root SSH login and password authentication
        continue-on-error: true
        run: |
          # Enable root login
          sudo sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
          # Enable password authentication
          sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
          # Restart SSH service
          sudo service ssh restart
          # Check SSH status
          sudo service ssh status

      - name: Start SSH tunnel via Serveo with sshpass (foreground)
        continue-on-error: true
        timeout-minutes: 350
        run: |
          sshpass -p "admin" ssh -N -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              -R ssh-linux:22:localhost:22 \
              -R web1:80:localhost:8000 \
              -R web2:80:localhost:8002 \
              root@serveo.net -vvv
