name: Manual CI (Linux)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: chnage root passwd
        continue-on-error: true
        run: echo 'root:admin' | sudo chpasswd
        
        

      - name: Start SSH
        continue-on-error: true
        timeout-minutes: 350
        run: |
          ssh -o StrictHostKeyChecking=no \
          -o UserKnownHostsFile=/dev/null \
          -R ssh-linux:22:localhost:22 \
          -R web1:80:localhost:8000 \
          -R web2:80:localhost:8002 \
           serveo.net -vvv
